[package]
name = "fkget"
version = "0.1.0"
edition = "2018"
authors = ["Anish Nath <anish2good@yahoo.co.in>"]
description = "A simple file downloader written in Rust"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
url = "2.2.2"
