name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: forest-${{ github.ref_name }}-linux-amd64.zip
          - os: macos-latest
            file: forest-${{ github.ref_name }}-macos-amd64.zip
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Apt Dependencies
        if: contains(matrix.os, 'ubuntu')
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: sudo make install-deps
      - name: Homebrew Utils
        if: contains(matrix.os, 'macos')
        run: |
          brew install --verbose coreutils protobuf
          protoc --version
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        timeout-minutes: 5
        continue-on-error: true
      - name: Cargo Build
        run: cargo build --release --bin fkget
      - name: Compress Binary
        run: |
          mkdir -p fkget-${{ github.ref_name }}
          cp -v target/release/fkget  fkget-${{ github.ref_name }}
          sha256sum fkget-${{ github.ref_name }}/fkget > fkget-${{ github.ref_name }}/fkget.sha256
          zip -r ${{ matrix.file }} forest-${{ github.ref_name }}
      - name: Upload Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ${{ matrix.file }}
          asset_name: ${{ matrix.file }}
          tag: ${{ github.ref_name }}
          overwrite: true
          prerelease: true